# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_assist', '0002_submittedimage_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('path', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
